language: node_js
rvm: 2.6
node_js:
 - 10
before_install:
  - yarn install
install: bundle install
script: "yarn build && rm .gitignore"
sudo: false
cache:
  - bundler
  - yarn
branches:
  only:
  - production
deploy:
  provider: pages
  target-branch: master
  skip-cleanup: true
  github-token: $githubToken
  keep-history: true
  on:
    branch: production
